// app/layout.tsx

import Navbar from './navbar'; // Import the Navbar component
import type { Metadata } from 'next';
import { JetBrains_Mono } from 'next/font/google';
import { cookies } from 'next/headers';
import { ButtonSoundProvider } from './providers/button-sound-provider';
import { GlobalLoadingProvider } from './providers/loading-provider';
import './globals.css';

const jetBrainsMono = JetBrains_Mono({
  variable: '--font-jetbrains-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  const cookieStore = await cookies();
  const bgAnim = cookieStore.get('bg-anim')?.value;
  const hintsCookie = cookieStore.get('hints')?.value;
  const htmlAnim = bgAnim === 'off' ? 'off' : undefined;
  const htmlHints = hintsCookie === 'off' ? 'off' : undefined;

  return (
    <html lang="en" data-bg-anim={htmlAnim} data-hints={htmlHints}>
      <body
        className={`${jetBrainsMono.variable} ${jetBrainsMono.className} antialiased`}
        data-bg-anim={htmlAnim}
        data-hints={htmlHints}
        suppressHydrationWarning
      >
        <ul className="background">
   <li></li>
   <li></li>
   <li></li>
   <li></li>
   <li></li>
   <li></li>
   <li></li>
</ul>
        {/*<Navbar />*/}
        <ButtonSoundProvider>
          <GlobalLoadingProvider>{children}</GlobalLoadingProvider>
        </ButtonSoundProvider>
      </body>
    </html>
  );
}


